services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crowndine-image
    container_name: crowndine-app
    restart: always
    env_file:
      - dev.env
    environment:
      DATABASE_HOST: crowndine_db
      REDIS_HOST: crowndine_redis
      RABBITMQ_HOST: crowndine_rabbitmq
    ports:
      - "8080:8080"
    networks:
      - crowndine_net

networks:
  crowndine_net:
    external: true
    name: crowndine_net

#docker compose up -d